using System;
using System.Threading;
using System.Threading.Tasks;
using WarehouseService;

namespace Warehouse
{
    public class SOAP
    {
        public SOAP()
        {
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        //runner
        public async Task RunExample()
        {
            //instatiate web service from 'Connected Services' reference through Visual Studio tool
            var service = new EmulatorServiceClient();

            
            //print response of GetInventoryAsync()
            var response = await service.GetInventoryAsync();
            Console.WriteLine(response);
            
        }
        
    }
}
