using System;
using System.Threading;
using System.Threading.Tasks;
using WarehouseService;

namespace Warehouse
{
    public class SOAP
    {
        private string SOAPmessage;
        private EmulatorServiceClient service;
        public SOAP()
        {
            service = new EmulatorServiceClient();
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        public async Task pickItem(int trayId)
        {
            var response = await service.PickItemAsync(trayId);
            Console.WriteLine(response);
        }
        public async Task<String> getInventory()
        {
            var response = await service.GetInventoryAsync();
            SOAPmessage = response;
            return SOAPmessage;
        }

        public async Task insertItem(int trayId, string name)
        {
            var response = await service.InsertItemAsync(trayId, name);
            SOAPmessage = response;
            Console.WriteLine(response);
        }
    }
}
