using System;
using System.Threading;
using System.Threading.Tasks;
using WarehouseService;

namespace Warehouse
{
    public class SOAP
    {
        private string SOAPmessage;
        private EmulatorServiceClient service;
        public SOAP()
        {
            service = new EmulatorServiceClient();
        }

        //Check out the 'Connected Services>WarehouseService>Reference.cs' file to see autogenerated code. Read green text at the top.

        public async Task pickItem(int trayId)
        {
            var response = await service.PickItemAsync(trayId);
            Console.WriteLine(response);
            //return response;
        }
        //runner
        public async Task<String> getInventory()
        {
            //instatiate web service from 'Connected Services' reference through Visual Studio tool
            //print response of GetInventoryAsync()
            var response = await service.GetInventoryAsync();
            SOAPmessage = response;
            //Console.WriteLine(SOAPmessage + "\n"); //Print message with a new line
            return SOAPmessage;
        }
    }
}
